name: SpigotLifesteal
main: com.technodot.lifesteal.SpigotLifesteal
version: 1.0
api-version: 1.19
author: TechnoDot
description: Lifesteal for Spigot!
commands:
    withdraw:
        description: Withdraws a heart from yourself.
        usage: /<command>
    free:
        description: Debug command that gives you a free heart item.
        usage: /<command>
    reset:
        description: Debug command that resets your heart count.
        usage: /<command>