name: SpigotLifesteal
main: com.technodot.lifesteal.SpigotLifesteal
version: 1.0
api-version: 1.19
author: TechnoDot
description: Lifesteal for Spigot!
commands:
    withdraw:
        description: Withdraws a heart from yourself.
        usage: /<command>