name: PluginBuilder
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - name: Build With Gradle
        run: |
         ./gradlew jar
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV
          echo "snapshotVersion=5.5-SNAPSHOT" >> $GITHUB_ENV
          echo "artifactPath=$(pwd)/builds" >> $GITHUB_ENV
      
      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SpigotLifesteal.jar
          path: ${{ env.artifactPath }}/Plugin-${{ env.snapshotVersion }}.jar
