name: PluginBuilder
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: SpraxDev/Action-SpigotMC@v4
        with:
          versions: 1.19.4
          generateSrc: true

      - run: ls bin

#      - uses: actions/upload-artifact@v3
#        with:
#          name: SpigotBuild
#          path: spigot-1.19.4.jar
